# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Runhua (Ivan) Xiao # Defaults to "Your New Jekyll Site"
name: Runhua (Ivan) Xiao [cite: 1]
email: rhxiao@ucdavis.edu [cite: 1]
description: >- # this means to ignore newlines until "baseurl:"
  PhD Candidate at UC Davis specializing in freight transportation systems, 
  urban mobility, transportation emissions, sustainable logistics, 
  and data-driven modeling. [cite: 1, 2, 3] 
  # (Replace with your preferred bio if different)
baseurl: "" # the subpath of your site, e.g. /blog. If your site is at https://username.github.io, leave this blank.
url: "https://YOUR_GITHUB_USERNAME.github.io" # Replace YOUR_GITHUB_USERNAME with your actual GitHub username
twitter_username: YOUR_TWITTER_USERNAME # Replace with your Twitter username (optional)
github_username:  YOUR_GITHUB_USERNAME # Replace with your GitHub username
linkedin_username: ivanrxiao # Extracted from your CV [cite: 1]
scholar_userid: YOUR_GOOGLE_SCHOLAR_ID # Replace with your Google Scholar User ID (optional)
orcid_id: YOUR_ORCID_ID # Replace with your ORCID ID (optional)

# Avatar
avatar: /images/profile.jpg # Replace with the path to your avatar image, e.g., /assets/images/profile.jpg (optional)

# Analytics
google_analytics: YOUR_GOOGLE_ANALYTICS_ID # Replace with your Google Analytics ID, e.g. UA-XXXXXXXX-X or G-XXXXXXXXXX (optional)

# Build settings
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes@4.24.0" # This is an example, common theme. Change if your template uses a different one or none.
# theme: minimal-mistakes-jekyll # Another way to specify a theme, if it's installed as a gem

# Plugins (some common ones, your theme might have its own list)
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  # - jekyll-gist # If you plan to embed GitHub Gists
  # - jekyll-scholar # If your theme uses this for publications

# Locale (Language and regional settings)
locale: "en-US" # Or "en", "zh-CN", etc. based on your preference

# Author information (often used by themes like Minimal Mistakes for structured data and author box)
author:
  name: Runhua (Ivan) Xiao [cite: 1]
  avatar: /assets/images/YOUR_AVATAR_FILENAME.jpg # Should be same as above
  bio: "PhD Candidate in Civil and Environmental Engineering at UC Davis." # A slightly shorter bio, can be same as description or different
  location: "Davis, CA" # Optional
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square" # Font Awesome icon
      url: "mailto:rhxiao@ucdavis.edu" [cite: 1]
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://YOUR_GITHUB_USERNAME.github.io" # Your main site URL
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/ivanrxiao" [cite: 1]
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/YOUR_GITHUB_USERNAME"
    # - label: "Twitter"
    #   icon: "fab fa-fw fa-twitter-square"
    #   url: "https://twitter.com/YOUR_TWITTER_USERNAME"
    # - label: "Google Scholar"
    #   icon: "fas fa-fw fa-graduation-cap" # Or use a specific Google Scholar icon if available
    #   url: "https://scholar.google.com/citations?user=YOUR_GOOGLE_SCHOLAR_ID"
    # - label: "ORCID"
    #   icon: "fab fa-fw fa-orcid" # Or use a specific ORCID icon
    #   url: "https://orcid.org/YOUR_ORCID_ID"

# Defaults for collections (e.g., posts, projects). This depends heavily on your chosen theme/template.
# Example for a blog posts collection:
# defaults:
#   - scope:
#       path: ""
#       type: "posts"
#     values:
#       layout: "single" # Default layout for posts
#       author_profile: true # Show author profile on posts
#       read_time: true
#       comments: true
#       share: true
#       related: true
#   # Example for pages:
#   - scope:
#       path: "_pages"
#       type: "pages"
#     values:
#       layout: "single"
#       author_profile: true

# Footer content / Navigation (highly theme-dependent)
# footer_links:
#   - title: "Home"
#     url: "/"
#   - title: "About"
#     url: "/about/"
#   - title: "CV"
#     url: "/assets/pdf/CV_RunhuaXiao_202505.pdf" # Assuming you might link to your CV pdf

# ---
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
